URL2: Fix implicit null declaration
pear/Net_URL2 pull request #14
Opened 2024-11-25 14:50 UTC by reedy

https://wiki.php.net/rfc/deprecate-implicitly-nullable-types

Fixed: https://pear.php.net/bugs/bug.php?id=28649

2024-11-25 15:02 UTC, reedy commented
This probably does require a newer version of PHP than 5.1.6 as per https://github.com/pear/Net_URL2/blob/master/composer.json#L34...

But when CI seemingly isn't working etc... :)

Started fixing that in https://github.com/pear/Net_URL2/pull/15

2024-11-25 18:34 UTC, reedy commented
> This probably does require a newer version of PHP than 5.1.6 as per https://github.com/pear/Net_URL2/blob/master/composer.json#L34...

7.1.0 it would seem - https://3v4l.org/F0lJH

![Screenshot 2024-11-25 at 18 34 12](https://github.com/user-attachments/assets/00164a90-8668-4766-bd7f-123b64adf74e)

2024-11-25 20:38 UTC, hakre requested changes
Thanks for reporting this, please use the opportunity to touch this for PHP 9.0 forwards compatibility and make the parameter non-optional.

This not only improves the code but also retains backwards compatibility.

2024-11-25 22:10 UTC, reedy commented
> This not only improves the code but also retains backwards compatibility.

At some point, supporting such old PHP versions doesn't make a lot of sense... Though, I guess when we can do it without breaking backwards compatability...

I guess I should update https://github.com/pear/Net_URL2/pull/15 to not change the required PHP version then too?

2024-11-25 22:20 UTC, hakre commented
> > This not only improves the code but also retains backwards compatibility.
> 
> At some point, supporting such old PHP versions doesn't make a lot of sense... Though, I guess when we can do it without breaking backwards compatability...

Yes, and thinking: this supports PHP 9.0 which is the opposite of old.

> 
> I guess I should update #15 to not change the required PHP version then too?

Ah #15, yes, please update.

2024-11-25 22:22 UTC, reedy commented
> > > This not only improves the code but also retains backwards compatibility.
> > 
> > 
> > At some point, supporting such old PHP versions doesn't make a lot of sense... Though, I guess when we can do it without breaking backwards compatability...
> 
> Yes, and thinking: this supports PHP 9.0 which is the opposite of old.

Well, I was more meaning 5.6 (and 5.1 as per composer.json currently)

> > I guess I should update #15 to not change the required PHP version then too?
> 
> Ah #15, yes, please update.

Already done! :)

2024-11-25 22:48 UTC, hakre commented
> Well, I was more meaning 5.6 (and 5.1 as per composer.json currently)

There is no need to change composer.json now, so that is not an issue. But if, then I'm totally with you that one needs to take many more things into consideration including which PHP versions are supported.

For the deprecation message btw., I've found it helpful in some more projects already to highlight some places for smaller refactorings that untangle needless null defaults and even default values at all. The analysis of existing code presented in the RFC only scratches the surface IMHO.

2024-12-07 15:29 UTC, ashnazg approved these changes

2024-12-07 15:29 UTC, merged